---
# playbook to deploy this executable.  ansible command is as follows...
#
# ansible-playbook --ask-pass --ask-become-pass  -i "idadcc.ucsd.edu," playbook.yml \
#   --extra-vars '{"hostname":"idadcc.ucsd.edu", "remoteuser":"dbargabus"}' --tags "datascope-extract-install"
#
#   replace hostname and remoteuser values as needed

- hosts: "{{ hostname }}"
  remote_user: "{{ remoteuser }}"

  vars:
    tmp_dir: "/tmp"
    src_dir: "/usr/local/src"
    ida_dir: "/usr/local/ida"
    local_bin_dir: "/usr/local/bin"

  tasks:
      - name: Directory for download of source must exist
        file:
          path: "{{ src_dir }}"
          state: directory
        become: true
        tags:
        - datascope-extract-install

      - name: Change group
        ansible.builtin.file:
          path: '{{ ida_dir }}'
          state: directory
          recurse: yes
          group: idadcg
        become: true
        tags:
        - datascope-extract-install

      - name: Change file permissions
        ansible.builtin.file:
          path: '{{ ida_dir }}'
          state: directory
          mode: '0775'
        become: true
        tags:
        - datascope-extract-install

      - name: get datascope-extract repo
        git:
            repo: 'git@github.com:ProjectIDA/datascope-extract.git'
            dest: '{{ ida_dir }}/datascope-extract'
        tags:
        - datascope-extract-install

      - name: Change file ownership, group
        ansible.builtin.file:
          path: '{{ ida_dir }}/datascope-extract'
          state: directory
          recurse: yes
          owner: idadcc
          group: idadcg
        become: true
        tags:
        - datascope-extract-install

      - name: Change file permissions
        ansible.builtin.file:
          path: '{{ ida_dir }}/datascope-extract'
          state: directory
          mode: '0775'
        become: true
        tags:
        - datascope-extract-install

      - name: install extract_datascope
        copy:
          src: '{{ ida_dir }}/datascope-extract/extract_datascope'
          dest: '{{ local_bin_dir }}/extract_datascope'
          remote_src: 'yes'
          owner: idadcc
          group: idadcc
          mode: 0775
        become: true
        tags:
        - datascope-extract-install
